security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG
#    com:
#      netflix: INFO
#        eureka: INFO #OFF
#        discovery: INFO #OFF

##### spring.cloud.services.registrationMethod #####
# To change value of spring.cloud.services.registrationMethod to 
# "direct" (default is "route"), add "c2c" to active profiles

ribbon: # <---NEW SECTION
  IsSecure: false

#spring:
#  rabbitmq:
#    addresses: ${vcap.services.cloud-bus.credentials.http_api_uris:http://localhost:5672}
