security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG
    com:
      netflix:
        eureka: ERROR
        discovery: ERROR

spring: # <---NEW SECTION
  cloud:
    services:
      registrationMethod: direct #route #direct

ribbon: # <---NEW SECTION
  IsSecure: false

#spring:
#  rabbitmq:
#    addresses: ${vcap.services.cloud-bus.credentials.http_api_uris:http://localhost:5672}
